version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.papermc.paper:paper-api"
        update-types: ["version-update:semver-patch"]
