name: Build and Release Plugin

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Get current version from the pom.xml
        id: get_version
        run: echo "VERSION=$(awk -F '[<>]' '/<version>/ {print $3; exit}' pom.xml)" >> $GITHUB_ENV

      - name: Upload JAR to release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
